# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo Material"
license = "MIT"
licenselink = "https://github.com/sachu92/hugo-material/blob/master/LICENSE.md"
description = "Material design theme based on MUICSS"
homepage = "http://github.com/sachu92/hugo-material/"
tags = ["material", "responsive", "portfolio"]
features = []
min_version = "0.41"

[author]
  name = "Sachin Krishnan T V"
  homepage = "https://sktv.page"

